// Auto generated by utensor-cli

#ifndef __MODELS_IRIS_MODEL_H
#define __MODELS_IRIS_MODEL_H
#include "uTensor/core/context.hpp"
void get_iris_model_ctx(Context& ctx, Tensor* input_0);
#endif // __MODELS_IRIS_MODEL_H