// Auto generated by utensor-cli

#include <stdint.h>

const int inline_MatMul_eightbit_x__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_MatMul_eightbit_x__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_w_fc1_0 [ 12 ] = {  0.23197283,  0.12824345,  -0.16374114,  0.3662638,  -0.31484145,  -0.4200752,  -0.7215176,  0.14573216,  0.53653383,  -0.24337873,  0.07730086,  0.27031916,  };
#include <stdint.h>

const int inline_MatMul_eightbit_w_fc1__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_MatMul_eightbit_w_fc1__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_b_fc1_0 [ 3 ] = {  0.21981989,  0.10059899,  -0.020418929,  };
#include <stdint.h>

const int inline_logits_eightbit_b_fc1__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_logits_eightbit_b_fc1__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const int inline_y_pred_dimension_0 [ 1 ] = {  1,  };
