// Auto generated by utensor-cli

#include <stdint.h>

const int inline_MatMul_1_eightbit_x_1__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_MatMul_1_eightbit_x_1__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_W_fc_1_0 [ 3 ] = {  -0.22415209,  0.1715996,  0.25153497,  };
#include <stdint.h>

const int inline_MatMul_1_eightbit_W_fc_1__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_MatMul_1_eightbit_W_fc_1__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_bias_fc_1_0 [ 1 ] = {  0.1,  };
#include <stdint.h>

const int inline_logits_eightbit_bias_fc_1__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_logits_eightbit_bias_fc_1__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const int inline_y_pred_dimension_0 [ 1 ] = {  1,  };
