// Auto generated by utensor-cli

#include <stdint.h>

const int inline_MatMul_eightbit_x__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_MatMul_eightbit_x__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_w_fc1_0 [ 2 ] = {  0.99889445,  0.99921614,  };
#include <stdint.h>

const int inline_MatMul_eightbit_w_fc1__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_MatMul_eightbit_w_fc1__port__0_reduction_dims_0 [ 1 ] = {  0,  };
#include <stdint.h>

const float inline_b_fc1_0 [ 1 ] = {  1.0009985,  };
#include <stdint.h>

const int inline_y_pred_eightbit_b_fc1__port__0_reshape_dims_0 [ 1 ] = {  -1,  };
#include <stdint.h>

const int inline_y_pred_eightbit_b_fc1__port__0_reduction_dims_0 [ 1 ] = {  0,  };
