// Auto generated by utensor-cli

#ifndef __MODELS_LR_MODEL_H
#define __MODELS_LR_MODEL_H
#include "uTensor/core/context.hpp"
void get_lr_model_ctx(Context& ctx, Tensor* input_0);
#endif // __MODELS_LR_MODEL_H